<?php
	/**
	 * This file has all of the status code constants.
	 */

	// Success status codes.
	define(STATUS_CODE_SUCCESS_STORED_PROCEDURE, 201);
	define(STATUS_CODE_SUCCESS_ACCOUNT_CREATION, 202);
	define(STATUS_CODE_SUCCESS_ACCOUNT_UPDATED, 203);
	define(STATUS_CODE_SUCCESS_DATE_LOGIN_UPDATED, 204);
	define(STATUS_CODE_SUCCESS_PASSWORD_CHANGED, 205);
	define(STATUS_CODE_SUCCESS_CREDENTIALS_VALID, 206);
	define(STATUS_CODE_SUCCESS_EMAILED_NEW_PASSWORD, 207);
	define(STATUS_CODE_SUCCESS_FITNESS_LOCATIONS_UPDATED, 208);
	define(STATUS_CODE_SUCCESS_FITNESS_EQUIPMENT_UPDATED, 209);
	define(STATUS_CODE_SUCCESS_EXERCISE_PRIORITY_UPDATED, 210);
	define(STATUS_CODE_SUCCESS_ROUTINE_SAVED, 211);
	define(STATUS_CODE_SUCCESS_MUSCLE_GROUP_UPDATED, 212);
	define(STATUS_CODE_SUCCESS_MUSCLE_GROUP_SET, 213);
	
	// Failure status codes.
	define(STATUS_CODE_FAILURE_STORED_PROCEDURE, 501);
	define(STATUS_CODE_FAILURE_EMAIL_ERROR, 502);
	define(STATUS_CODE_FAILURE_ACCOUNT_CREATION, 503);
	define(STATUS_CODE_FAILURE_PASSWORD_INVALID, 504);
	define(STATUS_CODE_FAILURE_PASSWORD_CHANGE, 505);
	define(STATUS_CODE_FAILURE_CREDENTIALS_EMAIL_INVALID, 506);
	define(STATUS_CODE_FAILURE_CREDENTIALS_PASSWORD_INVALID, 507);
	define(STATUS_CODE_FAILURE_ACCOUNT_NOT_UPDATED, 508);
	define(STATUS_CODE_FAILURE_DATE_LOGIN_UPDATE, 509);
	define(STATUS_CODE_FAILURE_EMAILED_PASSWORD, 510);
	define(STATUS_CODE_FAILURE_FITNESS_LOCATIONS_UPDATE, 511);
	define(STATUS_CODE_FAILURE_FITNESS_EQUIPMENT_UPDATE, 512);
	define(STATUS_CODE_FAILURE_EXERCISE_PRIORITY_UPDATE, 513);
	define(STATUS_CODE_FAILURE_ROUTINE_SAVE, 514);
	define(STATUS_CODE_FAILURE_ROUTINE_EXISTS, 515);
	define(STATUS_CODE_FAILURE_MUSCLE_GROUP_UPDATED, 516);
	define(STATUS_CODE_FAILURE_MUSCLE_GROUP_SET, 517);
?>