<?php
	/**
	 * This file has all of the status code constants.
	 */

	// Success status codes.
	define(RESPONSE_SUCCESS_ACCOUNT_CREATION, 201);
	define(RESPONSE_SUCCESS_ACCOUNT_UPDATED, 202);
	define(RESPONSE_SUCCESS_DATE_LOGIN_UPDATED, 203);
	define(RESPONSE_SUCCESS_PASSWORD_CHANGE, 204);

	// Failure status codes.
	define(RESPONSE_FAILURE_EMAIL_ERROR, 501);
	define(RESPONSE_FAILURE_ACCOUNT_CREATION, 502);
	define(RESPONSE_FAILURE_PASSWORD_INVALID, 503);
	define(RESPONSE_FAILURE_PASSWORD_CHANGE, 504);
?>